-- +migrate Up

ALTER DATABASE coreroller SET TIMEZONE = 'UTC';
ALTER TABLE team ALTER COLUMN created_ts TYPE TIMESTAMP WITH TIME ZONE USING created_ts AT TIME ZONE 'UTC';
ALTER TABLE users ALTER COLUMN created_ts TYPE TIMESTAMP WITH TIME ZONE USING created_ts AT TIME ZONE 'UTC';
ALTER TABLE application ALTER COLUMN created_ts TYPE TIMESTAMP WITH TIME ZONE USING created_ts AT TIME ZONE 'UTC';
ALTER TABLE package ALTER COLUMN created_ts TYPE TIMESTAMP WITH TIME ZONE USING created_ts AT TIME ZONE 'UTC';
ALTER TABLE coreos_action ALTER COLUMN created_ts TYPE TIMESTAMP WITH TIME ZONE USING created_ts AT TIME ZONE 'UTC';
ALTER TABLE channel ALTER COLUMN created_ts TYPE TIMESTAMP WITH TIME ZONE USING created_ts AT TIME ZONE 'UTC';
ALTER TABLE groups ALTER COLUMN created_ts TYPE TIMESTAMP WITH TIME ZONE USING created_ts AT TIME ZONE 'UTC';
ALTER TABLE instance ALTER COLUMN created_ts TYPE TIMESTAMP WITH TIME ZONE USING created_ts AT TIME ZONE 'UTC';
ALTER TABLE instance_application ALTER COLUMN created_ts TYPE TIMESTAMP WITH TIME ZONE USING created_ts AT TIME ZONE 'UTC';
ALTER TABLE instance_application ALTER COLUMN last_check_for_updates TYPE TIMESTAMP WITH TIME ZONE USING last_check_for_updates AT TIME ZONE 'UTC';
ALTER TABLE instance_application ALTER COLUMN last_update_granted_ts TYPE TIMESTAMP WITH TIME ZONE USING last_update_granted_ts AT TIME ZONE 'UTC';
ALTER TABLE instance_status_history ALTER COLUMN created_ts TYPE TIMESTAMP WITH TIME ZONE USING created_ts AT TIME ZONE 'UTC';
ALTER TABLE event ALTER COLUMN created_ts TYPE TIMESTAMP WITH TIME ZONE USING created_ts AT TIME ZONE 'UTC';
ALTER TABLE activity ALTER COLUMN created_ts TYPE TIMESTAMP WITH TIME ZONE USING created_ts AT TIME ZONE 'UTC';

-- +migrate Down

ALTER TABLE team ALTER COLUMN created_ts TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE users ALTER COLUMN created_ts TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE application ALTER COLUMN created_ts TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE package ALTER COLUMN created_ts TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE coreos_action ALTER COLUMN created_ts TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE channel ALTER COLUMN created_ts TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE groups ALTER COLUMN created_ts TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE instance ALTER COLUMN created_ts TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE instance_application ALTER COLUMN created_ts TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE instance_application ALTER COLUMN last_check_for_updates TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE instance_application ALTER COLUMN last_update_granted_ts TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE instance_status_history ALTER COLUMN created_ts TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE event ALTER COLUMN created_ts TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE activity ALTER COLUMN created_ts TYPE TIMESTAMP WITHOUT TIME ZONE;
